version: '3'
services:
  app:
    build: .
    container_name: app-container
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - mysql
      - redis
      - kafka
      - zookeeper
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    command: ["faust", "-A", "app", "worker", "-l", "info"]  # Run Faust worker inside the Docker container
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports: 
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    env_file:
      - .env
    ports: 
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports: 
      - 6379:6379
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  random_generator:
    container_name: random_generator
    build: ./datagen
    depends_on:
      - kafka
    restart: always
    networks:
      - app-network

volumes:
  mongo-data:
  mysql-data:

networks:
  app-network:
    driver: bridge
