version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    
      
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongodb
      - postgres
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - MONGO_HOST=${MONGO_URI}
      - POSTGRES_HOST=${DB_HOST}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - POSTGRES_HOST=postgres
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Nuevo Dockerfile específico
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

volumes:
  mongodb_data:
  postgres_data: