global:
  scrape_interval: 15s
  evaluation_interval: 15s


  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # Add MySQL monitoring
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-container:3306']

   # Add Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-container:6379']